name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: B-ART-DEV

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Validate required secrets
      - name: Validate required secrets
        run: |
          if [ -z "${{ secrets.IMAGE_NAME }}" ]; then
            echo "ERROR: IMAGE_NAME secret is not set!"
            exit 1
          fi
          if [ -z "${{ secrets.DOTENV }}" ]; then
            echo "ERROR: DOTENV secret is not set!"
            exit 1
          fi

      # 3️⃣ Build Docker image
      - name: Build Docker image
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          echo "Building Docker image $IMAGE_NAME:latest"
          docker build -t "$IMAGE_NAME:latest" -f Dockerfile .

      # 4️⃣ Tag Docker image with commit SHA
      - name: Tag Docker image with commit SHA
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          COMMIT_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker tag "$IMAGE_NAME:latest" "$IMAGE_NAME:$COMMIT_TAG"

      # 5️⃣ Push Docker image to Docker Hub
      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push "$IMAGE_NAME:latest"
          COMMIT_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker push "$IMAGE_NAME:$COMMIT_TAG"