name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: B-ART-DEV

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Docker image name
        run: echo "IMAGE_NAME=${{ secrets.IMAGE_NAME }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t "$IMAGE_NAME:latest" -f Dockerfile .

      - name: Tag Docker image with commit SHA
        run: |
          COMMIT_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker tag "$IMAGE_NAME:latest" "$IMAGE_NAME:$COMMIT_TAG"

      - name: Push Docker image
        if: github.event_name == 'push'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push "$IMAGE_NAME:latest"
          COMMIT_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker push "$IMAGE_NAME:$COMMIT_TAG"
