name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: B-ART-DEV  # access environment secrets

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set Docker image name from secret
      - name: Set Docker image name
        run: echo "IMAGE_NAME=${{ secrets.IMAGE_NAME }}" >> $GITHUB_ENV

      # 3. Build Docker image with :latest tag
      - name: Build Docker image
        run: |
          echo "Building Docker image: $IMAGE_NAME:latest"
          docker build -t "$IMAGE_NAME:latest" -f Dockerfile .

      # 4. Tag Docker image with commit SHA
      - name: Tag Docker image with commit SHA
        run: |
          COMMIT_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          echo "COMMIT_TAG=$COMMIT_TAG" >> $GITHUB_ENV
          docker tag "$IMAGE_NAME:latest" "$IMAGE_NAME:$COMMIT_TAG"
          echo "Tagged Docker image: $IMAGE_NAME:$COMMIT_TAG"

      # 5. Push Docker image to Docker Hub (only on push)
      - name: Push Docker image
        if: github.event_name == 'push'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          COMMIT_TAG: ${{ github.sha::7 }}
        run: |
          if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
            echo "Docker Hub secrets are missing!"
            exit 1
          fi

          echo "Logging in to Docker Hub as $DOCKER_USERNAME"
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

          echo "Pushing Docker image: $IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:latest"

          echo "Pushing Docker image: $IMAGE_NAME:$COMMIT_TAG"
          docker push "$IMAGE_NAME:$COMMIT_TAG"
