name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=randriamihamina/n0rsxduhfn8yrh08g5e16wu5sxed13:latest
          echo "Building Docker image: $IMAGE_NAME"
          docker build -t $IMAGE_NAME -f Dockerfile .

      # 3. Only log in and push if secrets are available
      - name: Push Docker image (only on push to repo)
        if: github.event_name == 'push'
        run: |
          echo "Logging in to Docker Hub"
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          IMAGE_NAME=randriamihamina/n0rsxduhfn8yrh08g5e16wu5sxed13:latest
          echo "Pushing Docker image: $IMAGE_NAME"
          docker push $IMAGE_NAME
